version: '3'
services:
  service:
    image: node:18
    container_name: hypnos-front
    tty: true
    ports:
      - '3000:3000'
    networks:
      - hypnos-nw
    volumes:
      - type: bind
        source: ../
        target: /app
    working_dir: /app
    env_file:
      - ../.env.local

networks:
  hypnos-nw:
    external: true
